export const nameAzmoon = 'نام آزمون'
export const mabhaseAzmoon = 'مبحث آزمون'
export const tedadeSoal = 'تعداد سوالات'
export const zamaneAzmoon = 'زمان آزمون (دقیقه)'
export const ijadeAzmoon = 'ایجاد آزمون'

export const soal = 'سوال'
export const tasvireMarbootbeSoal = 'تصویر مربوط به سوال'
export const gozineYek = 'گزینه یک'
export const gozineDo = 'گزینه دو'
export const gozineSe = 'گزینه سه'
export const gozineChahar = 'گزینه چهار'
